language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

env:
  global:
    - NODE_ENV=test

script:
  - yarn test
  - yarn build
after_success:
  - npm run coverage

deploy:
  provider: heroku
  app: uno-back
  api_key:
    secure: ${HEROKU_API_KEY}
  on:
    branch: release