dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "felberto-github"
    token:
      secure: ${SONAR_TOKEN}

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

env:
  global:
    - NODE_ENV=test

script:
  - npm run test --coverage --watchAll=false
  - npm run build

after_success:
  - npm run coverage
  - sonar-scanner

deploy:
  provider: heroku
  app: uno-client
  api_key:
    secure: ${HEROKU_API_KEY}
  on:
    branch: release