dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "felberto-github"
    token:
      secure: ${SONAR_TOKEN}

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

env:
  global:
    - NODE_ENV=test

jobs:
  include:
    - stage: test
      script:
        - npm test -- --coverage --watchAll=false
    - stage: build
      script:
        - npm run build
    - stage: sonar
      script:
        - npm test -- --coverage --watchAll=false
        - sonar-scanner
    - stage: deploy
      if: branch = release
      script:
        - npm run build
      deploy:
        provider: heroku
        app: uno-client
        api_key:
          secure: ${HEROKU_API_KEY}
        on:
          branch: release